name: mock_server
description: A mock server for local development using Dart Frog.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.0
  dart_frog_gen: ^2.0.0